# US locations for job posting filter: states, abbreviations, cities, and nationwide strings.
# All entries lowercase. Used by ingestor.location_matches_us_filters().

US_LOCATIONS: set[str] = {
    # Nationwide / generic US
    "united states",
    "usa",
    "u.s.",
    "u.s.a.",
    "us",
    "anywhere in the us",
    "nationwide",
    "continental us",
    "conus",
    # Alabama
    "alabama",
    "al",
    "birmingham",
    "montgomery",
    "huntsville",
    "mobile",
    "tuscaloosa",
    "hoover",
    "dothan",
    "auburn",
    "decatur",
    "madison",
    "florence",
    "gadsden",
    "vestavia hills",
    # Alaska
    "alaska",
    "ak",
    "anchorage",
    "fairbanks",
    "juneau",
    "sitka",
    "ketchikan",
    "wasilla",
    "kenai",
    "kodiak",
    "bethel",
    # Arizona
    "arizona",
    "az",
    "phoenix",
    "tucson",
    "mesa",
    "chandler",
    "scottsdale",
    "gilbert",
    "tempe",
    "glendale",
    "peoria",
    "surprise",
    "flagstaff",
    "yuma",
    "prescott",
    "casa grande",
    # Arkansas
    "arkansas",
    "ar",
    "little rock",
    "fort smith",
    "fayetteville",
    "springdale",
    "jonesboro",
    "rogers",
    "conway",
    "bentonville",
    "pine bluff",
    "hot springs",
    "north little rock",
    # California
    "california",
    "ca",
    "los angeles",
    "la",
    "san francisco",
    "sf",
    "san diego",
    "san jose",
    "fresno",
    "sacramento",
    "long beach",
    "oakland",
    "berkeley",
    "bakersfield",
    "anaheim",
    "santa ana",
    "riverside",
    "stockton",
    "irvine",
    "chula vista",
    "fremont",
    "san bernardino",
    "modesto",
    "fontana",
    "oxnard",
    "moreno valley",
    "huntington beach",
    "glendale",
    "santa clarita",
    "garden grove",
    "oceanside",
    "rancho cucamonga",
    "santa rosa",
    "ontario",
    "el monte",
    "corona",
    "pomona",
    "pasadena",
    "palo alto",
    "mountain view",
    "sunnyvale",
    "cupertino",
    "menlo park",
    "santa barbara",
    "ventura",
    "davis",
    "stanford",
    # Colorado
    "colorado",
    "co",
    "denver",
    "colorado springs",
    "aurora",
    "fort collins",
    "lakewood",
    "thornton",
    "arvada",
    "westminster",
    "pueblo",
    "centennial",
    "boulder",
    "greeley",
    "longmont",
    "loveland",
    "grand junction",
    # Connecticut
    "connecticut",
    "ct",
    "bridgeport",
    "new haven",
    "stamford",
    "hartford",
    "waterbury",
    "norwalk",
    "danbury",
    "new britain",
    "bristol",
    "meriden",
    "west haven",
    "milford",
    "middletown",
    "norwich",
    # Delaware
    "delaware",
    "de",
    "wilmington",
    "dover",
    "newark",
    "middletown",
    "smyrna",
    "milford",
    "seaford",
    "georgetown",
    "elsmere",
    # Florida
    "florida",
    "fl",
    "miami",
    "jacksonville",
    "tampa",
    "orlando",
    "st. petersburg",
    "st petersburg",
    "hialeah",
    "tallahassee",
    "fort lauderdale",
    "port st. lucie",
    "port st lucie",
    "cape coral",
    "pembroke pines",
    "hollywood",
    "gainesville",
    "miami beach",
    "coral springs",
    "clearwater",
    "palm bay",
    "pompano beach",
    "west palm beach",
    "lakeland",
    "davie",
    "miami gardens",
    "sunrise",
    "boca raton",
    "deltona",
    "plantation",
    "sarasota",
    "fort myers",
    "melbourne",
    "kissimmee",
    "naples",
    "delray beach",
    # Georgia
    "georgia",
    "ga",
    "atlanta",
    "augusta",
    "columbus",
    "macon",
    "savannah",
    "athens",
    "sandy springs",
    "south fulton",
    "roswell",
    "johns creek",
    "warner robins",
    "albany",
    "alpharetta",
    "marietta",
    "valdosta",
    "smyrna",
    "dunwoody",
    "rome",
    "peachtree city",
    # Hawaii
    "hawaii",
    "hi",
    "honolulu",
    "pearl city",
    "hilo",
    "kailua",
    "waipahu",
    "kaneohe",
    "mililani town",
    "kahului",
    "ewa gorge",
    "mililani mauka",
    # Idaho
    "idaho",
    "id",
    "boise",
    "meridian",
    "nampa",
    "idaho falls",
    "pocatello",
    "caldwell",
    "coeur d'alene",
    "twin falls",
    "lewiston",
    "post falls",
    "rexburg",
    "moscow",
    # Illinois
    "illinois",
    "il",
    "chicago",
    "chi",
    "aurora",
    "naperville",
    "joliet",
    "rockford",
    "springfield",
    "elgin",
    "peoria",
    "champaign",
    "urbana",
    "bloomington",
    "decatur",
    "arlington heights",
    "evanston",
    "schaumburg",
    "bolingbrook",
    "palatine",
    "skokie",
    "des plaines",
    "orland park",
    "tinley park",
    "oak lawn",
    "berwyn",
    "mount prospect",
    "normal",
    "wheaton",
    "hoffman estates",
    "oak park",
    "downers grove",
    "elmhurst",
    "glenview",
    "dekalb",
    "lombard",
    "belleville",
    # Indiana
    "indiana",
    "in",
    "indianapolis",
    "fort wayne",
    "evansville",
    "south bend",
    "carmel",
    "bloomington",
    "fishers",
    "hammond",
    "gary",
    "muncie",
    "lafayette",
    "terre haute",
    "noblesville",
    "greenwood",
    "kokomo",
    "anderson",
    "mishawaka",
    "lawrence",
    "jeffersonville",
    # Iowa
    "iowa",
    "ia",
    "des moines",
    "cedar rapids",
    "davenport",
    "sioux city",
    "iowa city",
    "waterloo",
    "ames",
    "west des moines",
    "ankeny",
    "dubuque",
    "council bluffs",
    "urbandale",
    "marion",
    "betendorf",
    # Kansas
    "kansas",
    "ks",
    "wichita",
    "overland park",
    "kansas city",
    "olathe",
    "topeka",
    "lawrence",
    "shawnee",
    "lenexa",
    "manhattan",
    "salina",
    "hutchinson",
    "leavenworth",
    "leawood",
    "dodge city",
    # Kentucky
    "kentucky",
    "ky",
    "louisville",
    "lexington",
    "bowling green",
    "owensboro",
    "covington",
    "richmond",
    "georgetown",
    "florence",
    "elizabethtown",
    "nicholasville",
    "independence",
    "frankfort",
    "henderson",
    "jeffersontown",
    # Louisiana
    "louisiana",
    "la",
    "new orleans",
    "baton rouge",
    "shreveport",
    "metairie",
    "lafayette",
    "lake charles",
    "kenner",
    "bossier city",
    "monroe",
    "alexandria",
    "houma",
    "marrero",
    "new iberia",
    "slidell",
    "sulphur",
    # Maine
    "maine",
    "me",
    "portland",
    "lewiston",
    "bangor",
    "south portland",
    "auburn",
    "biddeford",
    "sanford",
    "saco",
    "augusta",
    "westbrook",
    "waterville",
    "presque isle",
    # Maryland
    "maryland",
    "md",
    "baltimore",
    "frederick",
    "rockville",
    "gaithersburg",
    "bowie",
    "hagerstown",
    "annapolis",
    "college park",
    "salisbury",
    "laurel",
    "greenbelt",
    "cumberland",
    "takoma park",
    "hyattsville",
    "bethesda",
    "silver spring",
    "towson",
    "columbia",
    "germantown",
    # Massachusetts
    "massachusetts",
    "ma",
    "boston",
    "worcester",
    "springfield",
    "cambridge",
    "lowell",
    "brockton",
    "quincy",
    "lynn",
    "new bedford",
    "fall river",
    "barnstable",
    "lawrence",
    "somerville",
    "framingham",
    "haverhill",
    "waltham",
    "malden",
    "brookline",
    "medford",
    "taunton",
    "chicopee",
    "weymouth",
    "revere",
    "peabody",
    "methuen",
    "salem",
    "beverly",
    # Michigan
    "michigan",
    "mi",
    "detroit",
    "grand rapids",
    "warren",
    "sterling heights",
    "ann arbor",
    "lansing",
    "flint",
    "dearborn",
    "livonia",
    "troy",
    "westland",
    "farmington hills",
    "kalamazoo",
    "wyoming",
    "southfield",
    "rochester hills",
    "taylor",
    "pontiac",
    "saint clair shores",
    "royal oak",
    "novi",
    "dearborn heights",
    "battle creek",
    "saginaw",
    "kentwood",
    "east lansing",
    "roseville",
    "portage",
    # Minnesota
    "minnesota",
    "mn",
    "minneapolis",
    "st. paul",
    "st paul",
    "rochester",
    "duluth",
    "bloomington",
    "brooklyn park",
    "plymouth",
    "woodbury",
    "lakeville",
    "maple grove",
    "blaine",
    "eagan",
    "burnsville",
    "cottage grove",
    "apple valley",
    "eden prairie",
    "minnetonka",
    "mankato",
    "moorhead",
    "st. cloud",
    "st cloud",
    # Mississippi
    "mississippi",
    "ms",
    "jackson",
    "gulfport",
    "southaven",
    "hattiesburg",
    "biloxi",
    "meridian",
    "tupelo",
    "greenville",
    "olive branch",
    "horn lake",
    "clinton",
    "pearl",
    "vicksburg",
    "oxford",
    "starkville",
    # Missouri
    "missouri",
    "mo",
    "kansas city",
    "st. louis",
    "st louis",
    "springfield",
    "columbia",
    "independence",
    "lee's summit",
    "lees summit",
    "o'fallon",
    "ofallon",
    "st. joseph",
    "st joseph",
    "joplin",
    "st. charles",
    "st charles",
    "st. peters",
    "st peters",
    "blue springs",
    "florissant",
    "jefferson city",
    "cape girardeau",
    "wildwood",
    "chesterfield",
    # Montana
    "montana",
    "mt",
    "billings",
    "missoula",
    "great falls",
    "bozeman",
    "butte",
    "helena",
    "kalispell",
    "havre",
    "anaconda",
    "miles city",
    "belgrade",
    # Nebraska
    "nebraska",
    "ne",
    "omaha",
    "lincoln",
    "bellevue",
    "grand island",
    "kearney",
    "fremont",
    "hastings",
    "norfolk",
    "columbus",
    "papillion",
    "la vista",
    "scottsbluff",
    "south sioux city",
    # Nevada
    "nevada",
    "nv",
    "las vegas",
    "henderson",
    "reno",
    "north las vegas",
    "sparks",
    "carson city",
    "fernley",
    "elko",
    "mesquite",
    "boulder city",
    "fallon",
    "winnemucca",
    # New Hampshire
    "new hampshire",
    "nh",
    "manchester",
    "nashua",
    "concord",
    "derry",
    "dover",
    "rochester",
    "salem",
    "merrimack",
    "hudson",
    "londonderry",
    "keene",
    "bedford",
    "portsmouth",
    "goffstown",
    # New Jersey
    "new jersey",
    "nj",
    "newark",
    "jersey city",
    "paterson",
    "elizabeth",
    "edison",
    "woodbridge",
    "lakewood",
    "toms river",
    "clifton",
    "trenton",
    "camden",
    "brick",
    "cherry hill",
    "passaic",
    "union city",
    "old bridge",
    "gloucester",
    "east orange",
    "bayonne",
    "franklin",
    "north bergen",
    "vineland",
    "union",
    "hoboken",
    "perth amboy",
    "plainfield",
    "sayreville",
    "wayne",
    "irvington",
    "new brunswick",
    "hackensack",
    "kearny",
    "linden",
    "atlantic city",
    # New Mexico
    "new mexico",
    "nm",
    "albuquerque",
    "las cruces",
    "rio rancho",
    "santa fe",
    "roswell",
    "farmington",
    "clovis",
    "hobbs",
    "alamogordo",
    "carlsbad",
    "gallup",
    "deming",
    "los lunas",
    # New York
    "new york",
    "ny",
    "new york city",
    "nyc",
    "buffalo",
    "rochester",
    "yonkers",
    "syracuse",
    "albany",
    "new rochelle",
    "mount vernon",
    "schenectady",
    "utica",
    "white plains",
    "troy",
    "niagara falls",
    "binghamton",
    "freeport",
    "valley stream",
    "long beach",
    "spring valley",
    "ithaca",
    "elmira",
    "jamestown",
    "watertown",
    "poughkeepsie",
    "glens falls",
    "saratoga springs",
    "kingston",
    "middletown",
    "newburgh",
    "plattsburgh",
    "oswego",
    "oneonta",
    "cortland",
    "amsterdam",
    "geneva",
    "canandaigua",
    "batavia",
    # North Carolina
    "north carolina",
    "nc",
    "charlotte",
    "raleigh",
    "greensboro",
    "durham",
    "winston-salem",
    "fayetteville",
    "cary",
    "wilmington",
    "high point",
    "greenville",
    "asheville",
    "concord",
    "gastonia",
    "jacksonville",
    "chapel hill",
    "rocky mount",
    "burlington",
    "wilson",
    "huntersville",
    "kannapolis",
    "apex",
    "hickory",
    "goldsboro",
    # North Dakota
    "north dakota",
    "nd",
    "fargo",
    "bismarck",
    "grand forks",
    "minot",
    "west fargo",
    "williston",
    "dickinson",
    "mandan",
    "jamestown",
    "wahpeton",
    "devils lake",
    # Ohio
    "ohio",
    "oh",
    "columbus",
    "cleveland",
    "cincinnati",
    "toledo",
    "akron",
    "dayton",
    "parma",
    "canton",
    "youngstown",
    "lorain",
    "hamilton",
    "springfield",
    "kettering",
    "elyria",
    "lakewood",
    "cuyahoga falls",
    "middletown",
    "newark",
    "dublin",
    "beavercreek",
    "strongsville",
    "fairfield",
    "cleveland heights",
    "fairborn",
    "findlay",
    "warren",
    "lancaster",
    "lima",
    "huber heights",
    "worthington",
    "mason",
    "delaware",
    "brunswick",
    "athens",
    "kent",
    # Oklahoma
    "oklahoma",
    "ok",
    "oklahoma city",
    "tulsa",
    "norman",
    "broken arrow",
    "edmond",
    "lawton",
    "moore",
    "midwest city",
    "enid",
    "stillwater",
    "muskogee",
    "bartlesville",
    "owasso",
    "shawnee",
    "ponca city",
    # Oregon
    "oregon",
    "or",
    "portland",
    "salem",
    "eugene",
    "gresham",
    "hillsboro",
    "beaverton",
    "bend",
    "medford",
    "springfield",
    "corvallis",
    "albany",
    "tigard",
    "lake oswego",
    "keizer",
    "grant pass",
    "oregon city",
    "mcminnville",
    "redmond",
    "tualatin",
    "woodburn",
    # Pennsylvania
    "pennsylvania",
    "pa",
    "philadelphia",
    "philly",
    "pittsburgh",
    "allentown",
    "reading",
    "scranton",
    "bethlehem",
    "lancaster",
    "harrisburg",
    "altoona",
    "york",
    "state college",
    "erie",
    "wilkes-barre",
    "chester",
    "williamsport",
    "easton",
    "lebanon",
    "hazleton",
    "new castle",
    "johnstown",
    "monroeville",
    "plum",
    "bethel park",
    "mccandless",
    "norristown",
    "upper darby",
    "bensalem",
    "lower merion",
    "abington",
    # Rhode Island
    "rhode island",
    "ri",
    "providence",
    "warwick",
    "cranston",
    "pawtucket",
    "east providence",
    "woonsocket",
    "coventry",
    "cumberland",
    "north providence",
    "south kingstown",
    "west warwick",
    "johnston",
    "north kingstown",
    "newport",
    "bristol",
    "barrington",
    # South Carolina
    "south carolina",
    "sc",
    "charleston",
    "columbia",
    "north charleston",
    "mount pleasant",
    "rock hill",
    "greenville",
    "summerville",
    "sumter",
    "goose creek",
    "hilton head island",
    "florence",
    "spartanburg",
    "myrtle beach",
    "aiken",
    "anderson",
    "conway",
    "bluffton",
    "mauldin",
    "easley",
    # South Dakota
    "south dakota",
    "sd",
    "sioux falls",
    "rapid city",
    "aberdeen",
    "brookings",
    "watertown",
    "mitchell",
    "yankton",
    "pierre",
    "huron",
    "spearfish",
    "vermillion",
    # Tennessee
    "tennessee",
    "tn",
    "nashville",
    "memphis",
    "knoxville",
    "chattanooga",
    "clarksville",
    "murfreesboro",
    "jackson",
    "franklin",
    "johnson city",
    "bartlett",
    "hendersonville",
    "kingsport",
    "collierville",
    "cleveland",
    "smyrna",
    "germantown",
    "brentwood",
    "columbia",
    "spring hill",
    "antioch",
    "mount juliet",
    # Texas
    "texas",
    "tx",
    "houston",
    "san antonio",
    "dallas",
    "austin",
    "fort worth",
    "el paso",
    "arlington",
    "corpus christi",
    "plano",
    "laredo",
    "lubbock",
    "garland",
    "irving",
    "amarillo",
    "grand prairie",
    "mcallen",
    "frisco",
    "mckinney",
    "brownsville",
    "pasadena",
    "killeen",
    "mesquite",
    "midland",
    "denton",
    "abilene",
    "beaumont",
    "round rock",
    "odessa",
    "wichita falls",
    "richardson",
    "lewisville",
    "tyler",
    "college station",
    "pearland",
    "san angelo",
    "allen",
    "league city",
    "sugar land",
    "longview",
    "edinburg",
    "mission",
    "bryan",
    "baytown",
    "pharr",
    "temple",
    "missouri city",
    "flower mound",
    "north richland hills",
    "victoria",
    "new braunfels",
    "cedar park",
    "mansfield",
    "rowlett",
    "georgetown",
    "port arthur",
    "euless",
    "pflugerville",
    "belton",
    "waco",
    "carrollton",
    "cypress",
    "san marcos",
    "rockwall",
    "galveston",
    "grapevine",
    "bedford",
    "texas city",
    # Utah
    "utah",
    "ut",
    "salt lake city",
    "west valley city",
    "provo",
    "west jordan",
    "orem",
    "sandy",
    "ogden",
    "st. george",
    "st george",
    "layton",
    "taylorsville",
    "south jordan",
    "lehi",
    "logan",
    "murray",
    "draper",
    "bountiful",
    "riverton",
    "roy",
    "pleasant grove",
    "kearns",
    "tooele",
    "cottonwood heights",
    "spanish fork",
    "springville",
    "canyon rim",
    # Vermont
    "vermont",
    "vt",
    "burlington",
    "south burlington",
    "rutland",
    "barre",
    "montpelier",
    "winooski",
    "st. albans",
    "st albans",
    "newport",
    "vergennes",
    "essex junction",
    "bennington",
    "brattleboro",
    # Virginia
    "virginia",
    "va",
    "virginia beach",
    "norfolk",
    "chesapeake",
    "richmond",
    "arlington",
    "newport news",
    "alexandria",
    "hampton",
    "roanoke",
    "portsmouth",
    "suffolk",
    "lynchburg",
    "harrisonburg",
    "leesburg",
    "charlottesville",
    "danville",
    "blacksburg",
    "manassas",
    "petersburg",
    "fredericksburg",
    "winchester",
    "salem",
    "staunton",
    "hopewell",
    "waynesboro",
    "fairfax",
    "falls church",
    "vienna",
    # Washington
    "washington",
    "wa",
    "seattle",
    "spokane",
    "tacoma",
    "vancouver",
    "bellevue",
    "kent",
    "everett",
    "renton",
    "spokane valley",
    "federal way",
    "yakima",
    "bellingham",
    "kirkland",
    "kennewick",
    "auburn",
    "pasco",
    "marysville",
    "lakewood",
    "redmond",
    "shoreline",
    "richland",
    "sammamish",
    "burien",
    "olympia",
    "lynnwood",
    "edmonds",
    "bremerton",
    "puyallup",
    "issaquah",
    "wenatchee",
    "mukilteo",
    "walla walla",
    "pullman",
    "ellensburg",
    # Washington DC
    "district of columbia",
    "washington dc",
    "washington d.c.",
    "dc",
    "d.c.",
    # West Virginia
    "west virginia",
    "wv",
    "charleston",
    "huntington",
    "morgantown",
    "parkersburg",
    "wheeling",
    "weirton",
    "fairmont",
    "beckley",
    "martinsburg",
    "clarksburg",
    "south charleston",
    "st. albans",
    "teays valley",
    "bluefield",
    # Wisconsin
    "wisconsin",
    "wi",
    "milwaukee",
    "madison",
    "green bay",
    "kenosha",
    "racine",
    "appleton",
    "waukesha",
    "oshkosh",
    "eau claire",
    "janesville",
    "west allis",
    "la crosse",
    "sheboygan",
    "wauwatosa",
    "fond du lac",
    "new berlin",
    "wausau",
    "brookfield",
    "greenfield",
    "beloit",
    "manitowoc",
    "superior",
    "neenah",
    "fitchburg",
    "menomonee falls",
    # Wyoming
    "wyoming",
    "wy",
    "cheyenne",
    "casper",
    "laramie",
    "gillette",
    "rock springs",
    "sheridan",
    "green river",
    "evanston",
    "rawlins",
    "riverton",
    "cody",
    "douglas",
    "torrington",
    "worland",
}
